#!/usr/bin/env python3
"""Turn extracted command lines into the invocations block a page renders.

generate_pages already knows how to render ENRICHMENT[tool]["invocations"] --
a list of {"task", "cmd"} -- into the "Common invocations" section. Exactly
one tool populated it (mmls), and one page carries hand-written examples
(fls.md, which the generator preserves). The other 153 pages have none, which
is the largest measured gap in the guide.

The split of responsibility is the same one the rest of this project rests
on: the COMMAND is extracted verbatim from a retrieved page and never
composed, and only the one-line task description is written by a model. A
wrong description is a bad label on a real command; a composed command line
is something the reader pastes into a terminal.

The description is gated: it must be short, must not hedge, must not simply
restate the command, and must be grounded in the page the command came from.
Anything that fails is dropped and the command goes without a label rather
than with an invented one.

    python scripts/build_invocations.py --tools mactime icat tcpflow
    python scripts/build_invocations.py --auto 8
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
ROOT = HERE.parent
OUT = HERE / "invocations_data.py"

import sources          # noqa: E402
import invocations      # noqa: E402
import enrich_loop      # noqa: E402
from page_gaps import audit  # noqa: E402

PROMPT = """Here is a real command line for the tool `{tool}`, taken from \
documentation:

    {cmd}

And here is the surrounding text it appeared in:

{context}

Write ONE short line of at most 12 words saying what this command is FOR -- \
the job an analyst is doing when they run it. Not what the flags mean. Not a \
sentence. No trailing full stop.

Good: List deleted entries with full paths
Good: Carve JPEGs from unallocated space
Bad: This command uses the -r flag to recurse

Answer with the line only."""

HEDGE = re.compile(r"\b(this command|the command|it (is|can)|allows|used to|"
                   r"you can|in order to|various|etc\.)\b", re.I)


def describe(tool: str, cmd: str, context: str, worker) -> str | None:
    """A short label for the command, or None if it cannot be trusted."""
    name, base, model = worker
    raw = enrich_loop.ask(base, model,
                          PROMPT.format(tool=tool, cmd=cmd,
                                        context=context[:1200]))
    if not raw or raw.startswith("__ERROR__"):
        return None
    line = " ".join(raw.strip().splitlines()[0].split()).strip('"\'' )
    line = line.rstrip(".")
    if not (8 <= len(line) <= 90):
        return None
    if len(line.split()) > 14 or HEDGE.search(line):
        return None
    # Restating the command teaches nothing: "fls -rp on the image".
    flags = set(re.findall(r"(?<![\w-])-{1,2}[A-Za-z][\w-]*", cmd))
    if flags and sum(1 for f in flags if f in line) >= 2:
        return None
    if line.lower().startswith(tool.lower()):
        return None
    return line[0].upper() + line[1:]


def for_tool(tool: str, worker, limit: int = 6) -> list[dict]:
    found = invocations.invocations_for(tool, limit=limit)
    if not found:
        return []
    pages = {p.get("url"): (p.get("text") or "") for p in sources.corpus_for(tool)}
    out = []
    for rec in found:
        text = pages.get(rec["url"], "")
        i = text.find(rec["command"][:40])
        ctx = text[max(0, i - 500):i + 500] if i >= 0 else text[:1000]
        task = describe(tool, rec["command"], ctx, worker)
        if task:
            out.append({"task": task, "cmd": rec["command"], "src": rec["url"]})
    return out


def write(data: dict[str, list[dict]]) -> None:
    body = [
        '"""Worked command lines, extracted from real pages.',
        "",
        "Generated by scripts/build_invocations.py. Every `cmd` appeared",
        "character for character in the page named by `src`; only `task` was",
        "written, and it went through a gate. Do not edit by hand -- rerun the",
        "script. Hand-written invocations belong in ENRICHMENT, which wins.",
        '"""',
        "from __future__ import annotations",
        "",
        "INVOCATIONS: dict[str, list[dict]] = {",
    ]
    for tool in sorted(data):
        if not data[tool]:
            continue
        body.append(f"    {tool!r}: [")
        for r in data[tool]:
            body.append("        {")
            body.append(f"            'task': {r['task']!r},")
            body.append(f"            'cmd': {r['cmd']!r},")
            body.append(f"            'src': {r['src']!r},")
            body.append("        },")
        body.append("    ],")
    body.append("}")
    OUT.write_text("\n".join(body) + "\n", encoding="utf-8")


def load() -> dict[str, list[dict]]:
    try:
        sys.path.insert(0, str(HERE))
        import invocations_data
        import importlib
        importlib.reload(invocations_data)
        return dict(invocations_data.INVOCATIONS)
    except Exception:
        return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tools", nargs="*", default=[])
    ap.add_argument("--auto", type=int, default=0)
    a = ap.parse_args()

    have = load()
    tools = list(a.tools)
    if a.auto:
        gaps = [r["page"] for r in audit()
                if not r["examples"] and not r["gui"] and r["page"] not in have]
        tools += gaps[:a.auto]
    if not tools:
        print("pass --tools or --auto N")
        return 1

    for i, tool in enumerate(tools):
        worker = enrich_loop.WORKERS[i % len(enrich_loop.WORKERS)]
        recs = for_tool(tool, worker)
        print(f"{tool:16s} {len(recs)} invocations", flush=True)
        for r in recs:
            print(f"    # {r['task']}")
            print(f"    {r['cmd'][:100]}")
        if recs:
            have[tool] = recs
            write(have)          # persist per tool, not at the end
    print(f"\nwrote {OUT.name}: {len(have)} tools, "
          f"{sum(len(v) for v in have.values())} invocations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
