"""Worked command lines, extracted from real pages.

Generated by scripts/build_invocations.py. Every `cmd` appeared
character for character in the page named by `src`; only `task` was
written, and it went through a gate. Do not edit by hand -- rerun the
script. Hand-written invocations belong in ENRICHMENT, which wins.
"""
from __future__ import annotations

INVOCATIONS: dict[str, list[dict]] = {
    'affcat': [
        {
            'task': 'Output contents of AFF disk image files',
            'cmd': 'affcat version 3.7.22',
            'src': 'https://www.kali.org/tools/afflib/',
        },
    ],
    'affconvert': [
        {
            'task': 'Convert files between RAW and AFF formats',
            'cmd': 'affconvert version 3.7.22',
            'src': 'https://www.kali.org/tools/afflib/',
        },
    ],
    'affinfo': [
        {
            'task': 'Display AFF file metadata and hash validation results',
            'cmd': 'affinfo version 3.7.22',
            'src': 'https://www.kali.org/tools/afflib/',
        },
    ],
    'bdeinfo': [
        {
            'task': 'Retrieve BitLocker encryption details from a drive',
            'cmd': 'bdeinfo -p Password /dev/sda1',
            'src': 'https://manpages.ubuntu.com/manpages/bionic/man1/bdeinfo.1.html',
        },
        {
            'task': 'Extract BitLocker encryption details from disk image',
            'cmd': 'bdeinfo -o $((512*128)) image.dd',
            'src': 'https://www.aldeid.com/wiki/Category:Encryption/Bitlocker',
        },
        {
            'task': 'Extract BitLocker volume details including recovery key and encryption method',
            'cmd': 'bdeinfo -o $((512*2048)) ~/xmount_pount/Bitlocker_physisch_test.dd',
            'src': 'https://bebinary4n6.blogspot.com/2020/01/how-to-handle-bitlocker-encrypted.html',
        },
    ],
    'dc3dd': [
        {
            'task': 'Create forensic image of log file and verify integrity',
            'cmd': 'dc3dd 7.2.646 started at 2018-12-01 13:37:20 -0500',
            'src': 'https://www.kali.org/tools/dc3dd/',
        },
    ],
    'dumpcap': [
        {
            'task': 'Display dumpcap tool help information',
            'cmd': 'dumpcap -h',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
    ],
    'icat': [
        {
            'task': 'Extract file content from disk image using inode',
            'cmd': 'icat image.dd <inode> > file_recovered',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
        {
            'task': 'Recover file content by inode from disk image',
            'cmd': 'icat image.dd 1234 > recovered_file.txt',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
        {
            'task': 'Extract file data from evidence and compute MD5 hash',
            'cmd': 'icat -o 2048 "$EVIDENCE" 12345 | md5sum',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Recover deleted file from evidence image',
            'cmd': 'icat -r -o 2048 "$EVIDENCE" 54321 > recovered_file.bin',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'mactime': [
        {
            'task': 'Generate timeline of file events from MAC time data',
            'cmd': 'mactime -b body.txt -d > timeline.csv',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Generate timeline with file paths and timestamps',
            'cmd': 'mactime -b "$OUTPUT/body.txt" -d -z UTC > "$OUTPUT/timeline.csv"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Generate timeline of file events within specific date range',
            'cmd': 'mactime -b body.txt -d -z UTC 2026-01-14..2026-01-15 > incident_timeline.csv',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'ngrep': [
        {
            'task': 'Monitor SMTP traffic on all network interfaces',
            'cmd': 'ngrep -d any port 25',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Capture HTTP traffic details line by line',
            'cmd': 'ngrep -W byline port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search for specific strings in network traffic data',
            'cmd': "ngrep -w 'm' -I /tmp/dns.dump",
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search for specific data patterns in network capture files',
            'cmd': 'ngrep -tD ns3 -I /tmp/dns.dump',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search for HTTP traffic in a packet capture file',
            'cmd': 'ngrep -I /tmp/dns.dump port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Capture error messages in network syslog traffic',
            'cmd': "ngrep -d any 'error' port syslog",
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
    ],
    'tcpflow': [
        {
            'task': 'Decode TCP flows from pcap to extract HTTP data and files',
            'cmd': 'tcpflow -r eth0.pcap',
            'src': 'https://blog.rootshell.be/2009/04/15/forensics-reconstructing-data-from-pcap-files/',
        },
        {
            'task': 'Reconstruct network flows from multiple pcap files into output directory',
            'cmd': 'tcpflow -o out -a -l *.pcap',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
        {
            'task': 'Analyze network traffic by reconstructing flows from pcap file',
            'cmd': 'tcpflow -a -o outdir -Fk -r packets.pcap',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
        {
            'task': 'Extract HTTP attachments from network traffic',
            'cmd': 'tcpflow -e scan_http -o outdir host sundown',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
        {
            'task': 'Capture traffic between hosts and generate MD5 hashes for analysis',
            'cmd': 'tcpflow -X report.xml -e scan_md5 -o outdir -Fk host helios and \\( hot or ace \\)',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
    ],
}
