"""Worked command lines, extracted from real pages.

Generated by scripts/build_invocations.py. Every `cmd` appeared
character for character in the page named by `src`; only `task` was
written, and it went through a gate. Do not edit by hand -- rerun the
script. Hand-written invocations belong in ENRICHMENT, which wins.
"""
from __future__ import annotations

INVOCATIONS: dict[str, list[dict]] = {
    '7za': [
        {
            'task': 'Create password-protected archive with text files',
            'cmd': '7za a pw.7z *.txt -pSECRET',
            'src': 'https://thedeveloperblog.com/7-zip-examples',
        },
        {
            'task': 'Add Z files to 7z archive',
            'cmd': '7za.exe a archive.7z Z*.* -ssc',
            'src': 'https://thedeveloperblog.com/7-zip-examples',
        },
        {
            'task': 'Restore backup from 7z archive containing tar file',
            'cmd': '7za x -so tecmint_files.tar.7z | tar xf -',
            'src': 'https://www.tecmint.com/7zip-command-examples-in-linux/',
        },
        {
            'task': 'Create password-protected archive to secure sensitive data',
            'cmd': '7za a -p{password_here} tecmint_secrets.tar.7z',
            'src': 'https://www.tecmint.com/7zip-command-examples-in-linux/',
        },
    ],
    'AmcacheParser': [
        {
            'task': 'Extract execution data and SHA1 hashes from Amcache.hve for analysis',
            'cmd': 'AmcacheParser.exe -f "<EV>\\Windows\\AppCompat\\Programs\\Amcache.hve" -i --csv "<OUT>\\Amcache" --csvf amcache.csv',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
        {
            'task': 'Extract application data from Amcache hive with whitelist filtering',
            'cmd': 'AmcacheParser.exe -f "C:\\Temp\\amcache\\AmcacheWin10.hve" -w "c:\\temp\\whitelist.txt" --csv C:\\temp',
            'src': 'https://github.com/EricZimmerman/AmcacheParser',
        },
    ],
    'AppCompatCacheParser': [
        {
            'task': 'Extract ShimCache entries from SYSTEM hive for analysis',
            'cmd': 'AppCompatCacheParser.exe -f "<EV>\\Windows\\System32\\config\\SYSTEM" --csv "<OUT>\\ShimCache" --csvf shimcache.csv',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
    ],
    'EvtxECmd': [
        {
            'task': 'Normalize event logs into structured CSV format',
            'cmd': 'EvtxECmd.exe --sync',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
        {
            'task': 'Convert event logs to normalized CSV using community maps',
            'cmd': 'EvtxECmd.exe -f "<EV>\\...\\Security.evtx" --csv "<OUT>\\EVTX" --csvf security.csv',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
    ],
    'RECmd': [
        {
            'task': 'Extract user activity data from registry hive',
            'cmd': 'RECmd.exe -f "<EV>\\Users\\{user}\\NTUSER.DAT" --bn BatchExamples\\UserActivity.reb --csv "<OUT>\\Registry"',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
    ],
    'SrumECmd': [
        {
            'task': 'Extract app network usage from SRUM database',
            'cmd': 'SrumECmd.exe -f "<EV>\\Windows\\System32\\sru\\SRUDB.dat" -r "<EV>\\Windows\\System32\\config\\SOFTWARE" --csv "<OUT>\\SRUM"',
            'src': 'https://ridgelinecyber.com/resources/kape-ez-tools/',
        },
    ],
    'affconvert': [
        {
            'task': 'Convert between raw disk images and AFF files',
            'cmd': 'affconvert file1.raw',
            'src': 'https://manpages.debian.org/testing/afflib-tools/affconvert.1.en.html',
        },
        {
            'task': 'Convert between AFF and raw formats for data processing',
            'cmd': 'affconvert file1.raw file2.raw file3.raw',
            'src': 'https://manpages.debian.org/testing/afflib-tools/affconvert.1.en.html',
        },
    ],
    'bdeinfo': [
        {
            'task': 'Retrieve BitLocker encryption details from a drive',
            'cmd': 'bdeinfo -p Password /dev/sda1',
            'src': 'https://manpages.ubuntu.com/manpages/bionic/man1/bdeinfo.1.html',
        },
        {
            'task': 'Extract BitLocker encryption details from disk image',
            'cmd': 'bdeinfo -o $((512*128)) image.dd',
            'src': 'https://www.aldeid.com/wiki/Category:Encryption/Bitlocker',
        },
    ],
    'bdemount': [
        {
            'task': 'Mount BitLocker-encrypted partition with password',
            'cmd': 'bdemount -p Password /dev/sda1',
            'src': 'https://manpages.ubuntu.com/manpages/bionic/man1/bdemount.1.html',
        },
        {
            'task': 'Mount BitLocker-encrypted volume using recovery key',
            'cmd': 'bdemount -r 599907-126192-034078-378543-435050-262383-683309-100661 /dev/sda2 /mnt/fuse',
            'src': 'https://github.com/libyal/libbde/wiki/Mounting',
        },
        {
            'task': 'Decrypt and mount BitLocker-encrypted volume from raw image',
            'cmd': 'bdemount -r 599907-126192-034078-378543-435050-262383-683309-100661 -o 524288 image.raw x:',
            'src': 'https://github.com/libyal/libbde/wiki/Mounting',
        },
        {
            'task': 'Mount BDE volume from raw image for analysis',
            'cmd': 'bdemount -X allow_root -r 599907-126192-034078-378543-435050-262383-683309-100661 image.raw /mnt/fuse',
            'src': 'https://github.com/libyal/libbde/wiki/Mounting',
        },
    ],
    'binwalk': [
        {
            'task': 'Scan firmware for embedded files and file systems',
            'cmd': 'binwalk firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
        {
            'task': 'Extract embedded files from firmware image',
            'cmd': 'binwalk -e firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
        {
            'task': 'Detect encrypted or compressed sections via entropy analysis',
            'cmd': 'binwalk -E firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
    ],
    'blkcalc': [
        {
            'task': 'Map blkls address to original image location',
            'cmd': 'blkcalc -u 10146 images/wd0e.dd',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
    ],
    'blkls': [
        {
            'task': 'Extract unallocated data fragments from image',
            'cmd': 'blkls images/wd0e.dd > output/wd0e.blkls',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Extract unallocated space data from evidence',
            'cmd': 'blkls -A -o 2048 "$EVIDENCE" > unallocated.raw',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'bulk_extractor': [
        {
            'task': 'Carve NTFS MFT records from volume E',
            'cmd': 'bulk_extractor -E ntfsmft -o output \\\\.\\E:',
            'src': 'https://www.kazamiya.net/en/bulk_extractor-rec',
        },
        {
            'task': 'Extract files from disk image to output directory',
            'cmd': 'bulk_extractor -o bulk-out xp-laptop-2005-07-04-1430.img',
            'src': 'https://www.kali.org/tools/bulk-extractor/',
        },
        {
            'task': 'Extract gzip and utmp data from Linux disk image',
            'cmd': 'bulk_extractor -x all -e gzip -e utmp -o output Linux.E01',
            'src': 'https://www.kazamiya.net/en/bulk_extractor-rec',
        },
        {
            'task': 'Carve contiguous JPEGs from disk image',
            'cmd': 'bulk_extractor -o out_folder -S jpeg_carve_mode=2 /evidence/disk.img',
            'src': 'https://hacktricks.wiki/en/generic-methodologies-and-resources/basic-forensic-methodology/partitions-file-systems-carving/file-data-carving-recovery-tools.html',
        },
    ],
    'capinfos': [
        {
            'task': 'Generate tab-delimited report with pcap file metadata',
            'cmd': 'capinfos -TtEc *.pcap',
            'src': 'https://www.wireshark.org/docs/man-pages/capinfos.html',
        },
        {
            'task': 'Check duplicate packets in capture file',
            'cmd': 'capinfos -c dupes.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Generate detailed capture file analysis report',
            'cmd': 'capinfos mycapture.pcap',
            'src': 'https://www.wireshark.org/docs/man-pages/capinfos.html',
        },
        {
            'task': 'Generate tabular report of capture file details',
            'cmd': 'capinfos -T mycapture.pcap',
            'src': 'https://www.wireshark.org/docs/man-pages/capinfos.html',
        },
        {
            'task': 'Generate tab report with pcap file metadata',
            'cmd': 'capinfos -T -t -E -c *.pcap',
            'src': 'https://www.wireshark.org/docs/man-pages/capinfos.html',
        },
    ],
    'chainsaw': [
        {
            'task': 'Detect missing log entries and time gaps',
            'cmd': './chainsaw analyse gaps ./Logs/',
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
        {
            'task': 'Search event logs for mimikatz indicators in attack samples',
            'cmd': './chainsaw search mimikatz -i evtx_attack_samples/',
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
        {
            'task': 'Searching EVTX logs for specific event IDs',
            'cmd': "./chainsaw search -t 'Event.System.EventID: =4104' evtx_attack_samples/",
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
        {
            'task': 'Detect threats in event logs using Sigma rules',
            'cmd': './chainsaw hunt EVTX-ATTACK-SAMPLES/ -s sigma/ --mapping mappings/sigma-event-logs-all.yml',
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
    ],
    'clamscan': [
        {
            'task': 'Scan directory and subdirectories for malware',
            'cmd': 'clamscan --recursive .',
            'src': 'https://docs.clamav.net/manual/Usage/Scanning.html',
        },
        {
            'task': 'Scan directory for malware detection',
            'cmd': 'clamscan ~/Downloads/malware/',
            'src': 'https://christiant.io/clamav-guide',
        },
        {
            'task': 'Scan directory to detect malware',
            'cmd': 'clamscan -r ~/Downloads/malware/',
            'src': 'https://christiant.io/clamav-guide',
        },
        {
            'task': 'Scan malware directory for infected files',
            'cmd': 'clamscan -i -r ~/Downloads/malware/',
            'src': 'https://christiant.io/clamav-guide',
        },
    ],
    'dc3dd': [
        {
            'task': 'Verify data integrity during forensic imaging',
            'cmd': 'dc3dd if=/var/log/messages of=/tmp/dc3dd hash=sha512',
            'src': 'https://www.kali.org/tools/dc3dd/',
        },
    ],
    'dcfldd': [
        {
            'task': 'Overwrite disk with pattern to erase data securely',
            'cmd': 'dcfldd pattern="00FFAACC" of=/dev/sda',
            'src': 'https://braincraze.net/dcfldd-a-comprehensive-guide-and-usage-examples/',
        },
        {
            'task': 'Create zero-filled test file for analysis',
            'cmd': 'dcfldd if=/dev/zero of=test bs=50M count=2',
            'src': 'https://www.mankier.com/1/dcfldd',
        },
    ],
    'dd': [
        {
            'task': 'Clone hard disk from source to target',
            'cmd': 'dd if=/dev/sda of=/dev/sdb',
            'src': 'https://dforensic.blogspot.com/2013/12/digital-forensicsforensic-imaging-with.html',
        },
        {
            'task': 'Wipe hard disk by overwriting with zeros',
            'cmd': 'dd if=/dev/zero of=/dev/hda bs=4K conv=noerror,sync',
            'src': 'https://dforensic.blogspot.com/2013/12/digital-forensicsforensic-imaging-with.html',
        },
    ],
    'editcap': [
        {
            'task': 'Remove duplicate packets from capture file',
            'cmd': 'editcap -d dupes.pcap nodups.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Split capture into 200-packet segments',
            'cmd': 'editcap -c 200 dbad.pcap dbadsplit.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
    ],
    'esedbinfo': [
        {
            'task': 'Retrieve ESE database metadata and structure',
            'cmd': 'esedbinfo Windows.edb',
            'src': 'https://manpages.debian.org/unstable/libesedb-utils/esedbinfo.1.en.html',
        },
    ],
    'evtxexport': [
        {
            'task': 'Export Windows event log entries for analysis',
            'cmd': 'evtxexport -p c/ -r c/Windows/System32/config/ c/Windows/System32/winevt/Logs/Apllication.Evtx',
            'src': 'https://manpages.debian.org/unstable/libevtx-utils/evtxexport.1.en.html',
        },
        {
            'task': 'Export event logs to XML format from file',
            'cmd': 'evtxexport -f xml p1/Windows/System32/winevt/Logs/Application.evtx',
            'src': 'https://github.com/libyal/libevtx/wiki/Tools',
        },
    ],
    'ewfacquire': [
        {
            'task': 'Create EWF image from device or file',
            'cmd': 'ewfacquire /dev/sda',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Convert split optical disc RAW to EWF image',
            'cmd': 'ewfacquire -T optical.cue optical.iso',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Convert RAW image to EWF format',
            'cmd': 'ewfacquire -c best -m fixed -t myfile -S 1T -u [-q] myfile.raw',
            'src': 'https://forensics.wiki/libewf/',
        },
    ],
    'ewfexport': [
        {
            'task': 'Convert EWF image to RAW or another EWF format',
            'cmd': 'ewfexport image.E01',
            'src': 'https://forensics.wiki/libewf/',
        },
    ],
    'ewfinfo': [
        {
            'task': 'Check EWF image details post-acquisition',
            'cmd': 'ewfinfo /Cases/001/001_2017_USB_Gold.E01',
            'src': 'https://dfir.science/2017/11/EWF-Tools-working-with-Expert-Witness-Files-in-Linux.html',
        },
    ],
    'ewfmount': [
        {
            'task': 'Mount EWF image to a folder for forensic analysis',
            'cmd': 'ewfmount image.E01 <folder>',
            'src': 'https://kb.offsec.nl/tools/forensics/ewf-tools/',
        },
        {
            'task': 'Mount logical image to access files',
            'cmd': 'ewfmount -f files image.L01 mount_point',
            'src': 'https://forensics.wiki/libewf/',
        },
    ],
    'ewfverify': [
        {
            'task': 'Verify EWF image integrity and validity',
            'cmd': 'ewfverify image.E01',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Verify data integrity of E01 file against stored hash',
            'cmd': 'ewfverify -f files logical.E01',
            'src': 'https://www.mankier.com/1/ewfverify',
        },
    ],
    'ffind': [
        {
            'task': 'Find deleted files associated with inode 493',
            'cmd': 'ffind -a images/wd0e.dd 493',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Scripted analysis of evidence with ffind',
            'cmd': 'ffind -o 2048 "$EVIDENCE" 12345',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'file': [
        {
            'task': 'Identify file type and format',
            'cmd': 'file app.py',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
        {
            'task': 'Identify file MIME type for scripting or automation',
            'cmd': 'file -i script.py',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
        {
            'task': 'Identify file types and their MIME information',
            'cmd': 'file -b document.pdf',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
        {
            'task': 'Identify file type and MIME for analysis',
            'cmd': 'file -b -i photo.jpg',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
        {
            'task': 'Process a list of files to identify their types',
            'cmd': 'file -f filelist.txt',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
        {
            'task': 'Identify the actual file type of a symbolic link target',
            'cmd': 'file -L /usr/bin/python',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-the-file-command-to-identify-file-types-on-ubuntu/view',
        },
    ],
    'foremost': [
        {
            'task': 'Carve JPEGs, PDFs, DOCs, XLS from disk image',
            'cmd': 'foremost -t doc,jpg,pdf,xls -i image.dd',
            'src': 'https://www.kali.org/tools/foremost/',
        },
    ],
    'freshclam': [
        {
            'task': 'Maintain up-to-date virus databases with regular checks',
            'cmd': 'freshclam -d -c 2',
            'src': 'https://manpages.ubuntu.com/manpages/trusty/man1/freshclam.1.html',
        },
        {
            'task': 'Update virus database automatically',
            'cmd': 'freshclam --quiet',
            'src': 'https://codelucky.com/freshclam-command-linux/',
        },
        {
            'task': 'Update ClamAV virus database locally',
            'cmd': 'freshclam --datadir=.',
            'src': 'https://manpages.ubuntu.com/manpages/trusty/man1/freshclam.1.html',
        },
    ],
    'fsstat': [
        {
            'task': 'Identify inode group for deleted file recovery',
            'cmd': 'fsstat images/hda1.dd',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Analyze file system structure of evidence',
            'cmd': 'fsstat -o 2048 "$EVIDENCE"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Determine fragment ranges in disk image for file system analysis',
            'cmd': 'fsstat -t ufs images/wd0e.dd',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Analyze file system metadata structure',
            'cmd': 'fsstat -o "$OFFSET" "$EVIDENCE" > "$OUTPUT/fsstat.txt"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'hashcat': [
        {
            'task': 'Restore a paused hash cracking session using saved state',
            'cmd': 'hashcat --restore --session=my_session',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
        {
            'task': 'Coordinate distributed cracking to avoid redundant attempts',
            'cmd': 'hashcat --brain-server',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
        {
            'task': 'Crack SHA1 hashes using a wordlist to recover passwords',
            'cmd': 'hashcat -m 100 hashes.txt wordlist.txt',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
        {
            'task': 'Display backend info for performance tuning',
            'cmd': 'hashcat --backend-info',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
        {
            'task': 'Display available OpenCL devices for selection',
            'cmd': 'hashcat -I',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
        {
            'task': 'Test hardware performance for cracking speed',
            'cmd': 'hashcat -b',
            'src': 'https://pentesting.site/cheat-sheets/hashcat/',
        },
    ],
    'hfind': [
        {
            'task': 'Verify file hashes against known database',
            'cmd': 'hfind -i nsrl-md5 /usr/share/sleuthkit/NSRLFile.txt',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'icat': [
        {
            'task': 'Extract file content by inode from disk image',
            'cmd': 'icat image.dd <inode> > file_recovered',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
        {
            'task': 'Generate MD5 hash of extracted file data',
            'cmd': 'icat -o 2048 "$EVIDENCE" 12345 | md5sum',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Recover file from evidence by inode',
            'cmd': 'icat -r -o 2048 "$EVIDENCE" 54321 > recovered_file.bin',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'istat': [
        {
            'task': 'Retrieve inode details to identify deleted files',
            'cmd': 'istat images/wd0e.dd 493',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Recover deleted directory entries via inode blocks',
            'cmd': 'istat -b 2 images/hda9.dd 232',
            'src': 'https://github.com/sleuthkit/sleuthkit/wiki/FS_Analysis',
        },
        {
            'task': 'Analyze file system metadata of evidence',
            'cmd': 'istat -o 2048 "$EVIDENCE" 12345',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Inspect inode metadata from disk image',
            'cmd': './istat -f linux-ext2 /root/able2/able2.part2.dd 2139 | less',
            'src': 'https://cenif.gitbooks.io/forensic-guide-to-linux/content/x_advanced_forensic_tools/sleuthkit.html',
        },
    ],
    'jcat': [
        {
            'task': 'Extract text from specific disk sectors',
            'cmd': 'jcat -o 2048 "$EVIDENCE" 100 | strings | head -30',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'jls': [
        {
            'task': 'List file system journal entries from evidence',
            'cmd': 'jls -o 2048 "$EVIDENCE"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'log2timeline.py': [
        {
            'task': 'List available plugins and parser presets',
            'cmd': 'log2timeline.py --info',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-log2timeline.html',
        },
        {
            'task': 'Generate timeline from source data',
            'cmd': 'log2timeline.py --storage-file OUTPUT INPUT',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-log2timeline.html',
        },
        {
            'task': 'Generate Plaso storage file from raw disk image data',
            'cmd': 'log2timeline.py case_analysis.plaso /mnt/evidence/image.dd',
            'src': 'https://www.exam-labs.com/blog/mastering-plaso-timeline-analysis-in-dfir-investigations',
        },
        {
            'task': 'Extract targeted file events from storage image',
            'cmd': 'log2timeline.py -f filter --storage-file timeline.plaso test.vhd',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-log2timeline.html',
        },
        {
            'task': 'Generate timeline from VHD using Plaso storage',
            'cmd': 'log2timeline.py --logfile test.log --storage-file timeline.plaso test.vhd',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-log2timeline.html',
        },
    ],
    'mactime': [
        {
            'task': 'Generate timeline of file events from MAC time data',
            'cmd': 'mactime -b body.txt -d > timeline.csv',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Generate timeline with file paths and timestamps',
            'cmd': 'mactime -b "$OUTPUT/body.txt" -d -z UTC > "$OUTPUT/timeline.csv"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'md5sum': [
        {
            'task': 'Generate MD5 checksum to verify file integrity',
            'cmd': 'md5sum ravi.pdf',
            'src': 'https://www.tecmint.com/generate-verify-check-files-md5-checksum-linux/',
        },
        {
            'task': 'Verify files match stored checksums',
            'cmd': 'md5sum -c files.md5',
            'src': 'https://www.tecmint.com/generate-verify-check-files-md5-checksum-linux/',
        },
        {
            'task': "Verify multiple files' integrity with stored hashes",
            'cmd': 'md5sum --check hashes',
            'src': 'https://www.howtoforge.com/linux-md5sum-command/',
        },
    ],
    'mergecap': [
        {
            'task': 'Merge multiple pcap files into a single capture file',
            'cmd': 'mergecap *.pcap -w merged.pcapng',
            'src': 'https://tshark.dev/edit/mergecap/',
        },
        {
            'task': 'Merge two network capture files into a single unified pcap file',
            'cmd': 'mergecap -w compare.pcap a.pcap b-shifted.pcap',
            'src': 'https://www.wireshark.org/docs/man-pages/mergecap.html',
        },
        {
            'task': 'Merge capture files into single output file',
            'cmd': 'mergecap -a -w outoforder.pcap download-good.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
    ],
    'mraptor': [
        {
            'task': 'Analyze files for malicious macro content',
            'cmd': 'mraptor file.doc',
            'src': 'https://github.com/decalage2/oletools/blob/master/oletools/doc/mraptor.md',
        },
        {
            'task': 'Scan zipped files for malicious macros',
            'cmd': 'mraptor malicious_file.xls.zip -z infected',
            'src': 'https://github.com/decalage2/oletools/blob/master/oletools/doc/mraptor.md',
        },
    ],
    'msodde': [
        {
            'task': 'Detect malicious content in OLE documents',
            'cmd': 'msodde file.doc',
            'src': 'https://github.com/decalage2/oletools/wiki/msodde',
        },
        {
            'task': 'Extract all fields from a Word document for analysis',
            'cmd': 'msodde -a file.doc',
            'src': 'https://github.com/decalage2/oletools/wiki/msodde',
        },
    ],
    'ngrep': [
        {
            'task': 'Monitor SMTP traffic across all network interfaces',
            'cmd': 'ngrep -d any port 25',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Monitor HTTP traffic with line-based packet display on port 80',
            'cmd': 'ngrep -W byline port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search PCAP for specific string occurrences in packets',
            'cmd': "ngrep -w 'm' -I /tmp/dns.dump",
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search DNS dump for ns3 entries with timestamps and replay packets',
            'cmd': 'ngrep -tD ns3 -I /tmp/dns.dump',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search network dump for traffic on specific port',
            'cmd': 'ngrep -I /tmp/dns.dump port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
    ],
    'nping': [
        {
            'task': 'Test host reachability and open ports',
            'cmd': 'nping scanme.nmap.org',
            'src': 'https://nmap.org/book/nping-man.html',
        },
        {
            'task': 'Test target port responsiveness with two rounds',
            'cmd': 'nping --tcp -c 2 1.1.1.1 -p 100-102',
            'src': 'https://nmap.org/book/nping-man.html',
        },
        {
            'task': 'Testing network connectivity via echo server',
            'cmd': 'nping --echo-server "public" -e wlan0 -vvv',
            'src': 'https://nmap.org/book/nping-man.html',
        },
        {
            'task': 'Test network host with custom TCP packet parameters',
            'cmd': 'nping --tcp -p 80 --flags rst --ttl 2 192.168.1.1',
            'src': 'https://nmap.org/book/nping-man.html',
        },
        {
            'task': 'Send ICMP time-exceeded packets to test network path',
            'cmd': 'nping --icmp --icmp-type time --delay 500ms 192.168.254.254',
            'src': 'https://nmap.org/book/nping-man.html',
        },
        {
            'task': 'Test TCP port responsiveness across multiple hosts with delays',
            'cmd': 'nping --tcp -c 1 --delay 500ms 1.1.1.1 2.2.2.2 3.3.3.3 -p 137-139',
            'src': 'https://nmap.org/book/nping-man.html',
        },
    ],
    'objdump': [
        {
            'task': 'Show objdump version and supported formats',
            'cmd': 'objdump -v -i',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
        {
            'task': "Inspect executable's overall file header metadata",
            'cmd': 'objdump -f factorial',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
        {
            'task': 'Display executable file header information for analysis',
            'cmd': 'objdump -p factorial',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
        {
            'task': 'Display section headers to analyze object file structure',
            'cmd': 'objdump -h factorial',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
        {
            'task': 'Display all object file headers',
            'cmd': 'objdump -x factorial',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
        {
            'task': 'Analyze machine code instructions in executable sections',
            'cmd': 'objdump -d factorial',
            'src': 'https://www.thegeekstuff.com/2012/09/objdump-examples/',
        },
    ],
    'oledir': [
        {
            'task': 'List embedded objects in OLE files',
            'cmd': 'oledir file.doc',
            'src': 'https://github.com/decalage2/oletools/wiki/oledir',
        },
    ],
    'olevba': [
        {
            'task': 'Analyze VBA macros in documents for malicious code',
            'cmd': 'olevba file.doc',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Decode obfuscated strings in VBA macro for analysis',
            'cmd': 'olevba file.doc --decode',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Analyze document macros by revealing deobfuscated VBA code',
            'cmd': 'olevba file.doc --reveal',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
    ],
    'openssl': [
        {
            'task': 'Verify certificate validity and trust chain',
            'cmd': 'openssl verify cert.pem',
            'src': 'https://www.madboa.com/geek/openssl/',
        },
    ],
    'pdf-parser': [
        {
            'task': 'Extract malicious PDF content for analysis',
            'cmd': 'pdf-parser.py -f -w malpdf.1 > mal.1',
            'src': 'https://blog.didierstevens.com/programs/pdf-tools/',
        },
        {
            'task': 'Search PDF for JavaScript to detect malware',
            'cmd': 'pdf-parser.py –search javascript malware.pdf',
            'src': 'https://blog.didierstevens.com/programs/pdf-tools/',
        },
        {
            'task': 'Extract PDF encryption details for analysis',
            'cmd': 'python pdf-parser.py -o 16 Project#1542292355.pdf',
            'src': 'https://www.netscylla.com/blog/2018/11/19/PDF-Analysis.html',
        },
        {
            'task': 'Extract encrypted URLs from PDF file',
            'cmd': 'python pdf-parser.py -s /URI Project#1542292355.pdf',
            'src': 'https://www.netscylla.com/blog/2018/11/19/PDF-Analysis.html',
        },
    ],
    'photorec': [
        {
            'task': 'Recover files from raw disk image',
            'cmd': 'photorec image.dd to carve a raw disk image',
            'src': 'https://www.cgsecurity.org/wiki/PhotoRec_Step_By_Step',
        },
    ],
    'psort.py': [
        {
            'task': 'List available output modules for psort',
            'cmd': 'psort.py -o list',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
        {
            'task': 'List available analysis plugins for psort',
            'cmd': 'psort.py --analysis list',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
        {
            'task': 'List supported time zones for output formatting',
            'cmd': 'psort.py --output-time-zone list',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
        {
            'task': 'Check parameters for VirusTotal analysis plugin',
            'cmd': 'psort.py --analysis virustotal -h',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
        {
            'task': 'Filter timeline events using specified criteria',
            'cmd': 'psort.py -q timeline.plaso FILTER',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
        {
            'task': 'Extract and sort event data from Plaso storage',
            'cmd': 'psort.py -w test.log timeline.plaso',
            'src': 'https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html',
        },
    ],
    'r2': [
        {
            'task': 'Debug the ls program to analyze execution and behavior',
            'cmd': 'r2 -d ls',
            'src': 'https://book.rada.re/first_steps/commandline_flags.html',
        },
        {
            'task': 'Load existing project file',
            'cmd': 'r2 -p test',
            'src': 'https://book.rada.re/first_steps/commandline_flags.html',
        },
        {
            'task': 'Open raw binary for carving analysis',
            'cmd': 'r2 -n dump.bin',
            'src': 'https://hexmos.com/freedevtools/c/cmd/r2/',
        },
        {
            'task': 'Carve binaries by resizing to original size',
            'cmd': 'r2 -wnqc"r $sz" $a',
            'src': 'https://hexmos.com/freedevtools/c/cmd/r2/',
        },
        {
            'task': 'Analyze PowerPC 32-bit sub-binary within FAT file',
            'cmd': 'r2 -a ppc -b 32 ls.fat',
            'src': 'https://book.rada.re/first_steps/commandline_flags.html',
        },
        {
            'task': 'Apply script patches to target binary',
            'cmd': 'r2 -i patch.r2 target.bin',
            'src': 'https://book.rada.re/first_steps/commandline_flags.html',
        },
    ],
    'rahash2': [
        {
            'task': 'Encrypt string using rotation cipher with seed',
            'cmd': 'rahash2 -S 12333 -E ror -s hello',
            'src': 'https://github.com/radareorg/radare2/blob/master/man/rahash2.1',
        },
        {
            'task': 'Verify file integrity by comparing CRC32 hash to expected value',
            'cmd': 'rahash2 -qqa crc32 /bin/ls 63212007',
            'src': 'https://github.com/radareorg/radare2/blob/master/man/rahash2.1',
        },
        {
            'task': 'Verify file integrity and encode data with plugins',
            'cmd': 'rahash2 -L',
            'src': 'https://manpages.opensuse.org/Tumbleweed/radare2/rahash2.1.en.html',
        },
        {
            'task': 'List cryptographic plugins loaded',
            'cmd': 'rahash2 -L | grep ^c',
            'src': 'https://www.mankier.com/1/rahash2',
        },
        {
            'task': "Generate multiple hash values for a file's contents",
            'cmd': 'rahash2 -a all /bin/ls',
            'src': 'https://book.rada.re/tools/rahash2/rahash_tool.html',
        },
        {
            'task': 'Compute hash of file to verify integrity',
            'cmd': 'rahash2 -qqa md5 /bin/ls',
            'src': 'https://manpages.opensuse.org/Tumbleweed/radare2/rahash2.1.en.html',
        },
    ],
    'rasm2': [
        {
            'task': 'Assemble x86 instruction into machine code bytes',
            'cmd': "rasm2 -a x86 -b 32 'mov eax, 33'",
            'src': 'https://www.mankier.com/1/rasm2',
        },
        {
            'task': 'Disassemble hex bytes into assembly instructions',
            'cmd': 'rasm2 -d 90',
            'src': 'https://manpages.ubuntu.com/manpages/bionic/man1/rasm2.1.html',
        },
        {
            'task': 'List available architecture plugins for disassembly',
            'cmd': 'rasm2 -L',
            'src': 'https://book.rada.re/tools/rasm2/intro.html',
        },
        {
            'task': 'Convert between assembly instructions and hex representations',
            'cmd': "rasm2 -a java 'nop'",
            'src': 'https://book.rada.re/tools/rasm2/disassemble.html',
        },
        {
            'task': 'Disassemble hex bytes into assembly instructions',
            'cmd': "rasm2 -a x86 -b 32 -d '90'",
            'src': 'https://book.rada.re/tools/rasm2/disassemble.html',
        },
    ],
    'readelf': [
        {
            'task': 'Display ELF file header metadata',
            'cmd': 'readelf -h /bin/ls',
            'src': 'https://codelucky.com/readelf-command-linux/',
        },
        {
            'task': 'Examine ELF file section headers and their details',
            'cmd': 'readelf -S /bin/ls',
            'src': 'https://codelucky.com/readelf-command-linux/',
        },
        {
            'task': 'Inspect symbol table entries in /bin/ls binary',
            'cmd': 'readelf -s /bin/ls',
            'src': 'https://codelucky.com/readelf-command-linux/',
        },
        {
            'task': 'View program headers of /bin/ls executable',
            'cmd': 'readelf -l /bin/ls',
            'src': 'https://codelucky.com/readelf-command-linux/',
        },
        {
            'task': 'Examine dynamic linking information in executable',
            'cmd': 'readelf -d /bin/ls',
            'src': 'https://codelucky.com/readelf-command-linux/',
        },
    ],
    'regipy-diff': [
        {
            'task': 'Compare registry hives to identify differences',
            'cmd': 'regipy-diff NTUSER.dat NTUSER_modified.dat -o /tmp/diff.csv',
            'src': 'https://github.com/mkorman90/regipy',
        },
    ],
    'regipy-dump': [
        {
            'task': 'Dump registry hive data to JSON for analysis',
            'cmd': 'regipy-dump ~/Documents/TestEvidence/Registry/NTUSER-CCLEANER.DAT -o /tmp/output.json',
            'src': 'https://github.com/mkorman90/regipy',
        },
    ],
    'regipy-parse-header': [
        {
            'task': 'Parse and display Windows registry hive header metadata',
            'cmd': 'regipy-parse-header ~/Documents/TestEvidence/Registry/SYSTEM',
            'src': 'https://github.com/mkorman90/regipy',
        },
    ],
    'regipy-plugins-run': [
        {
            'task': 'Analyze SYSTEM hive using plugins to extract relevant data',
            'cmd': 'regipy-plugins-run ~/Documents/TestEvidence/Registry/SYSTEM -o /tmp/plugins_output.json',
            'src': 'https://github.com/mkorman90/regipy',
        },
    ],
    'scalpel': [
        {
            'task': 'Extract embedded files from disk image',
            'cmd': 'scalpel file.img -o output',
            'src': 'https://hacktricks.wiki/en/generic-methodologies-and-resources/basic-forensic-methodology/partitions-file-systems-carving/file-data-carving-recovery-tools.html',
        },
    ],
    'sha256sum': [
        {
            'task': 'Compute SHA256 hashes for multiple image files',
            'cmd': 'sha256sum *.jpg',
            'src': 'https://cheatdocs.org/sha256sum/',
        },
        {
            'task': 'Verify file integrity using SHA256 checksums',
            'cmd': 'sha256sum -c checksums.sha256',
            'src': 'https://cheatdocs.org/sha256sum/',
        },
        {
            'task': 'Create checksum file for integrity verification',
            'cmd': 'sha256sum file.zip > checksums.sha256',
            'src': 'https://cheatdocs.org/sha256sum/',
        },
        {
            'task': 'Verify files match checksums',
            'cmd': 'sha256sum -c checksums.sha256 --quiet',
            'src': 'https://cheatdocs.org/sha256sum/',
        },
        {
            'task': 'Verify files match checksums for integrity',
            'cmd': 'sha256sum -c checksums.sha256 --status',
            'src': 'https://cheatdocs.org/sha256sum/',
        },
    ],
    'sigfind': [
        {
            'task': 'Search evidence for files with AA55 signature',
            'cmd': 'sigfind -o 510 -l AA55 "$EVIDENCE"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'srch_strings': [
        {
            'task': 'Search evidence files for password-related strings',
            'cmd': 'srch_strings -a -t d "$EVIDENCE" | grep -i "password"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'ssdeep': [
        {
            'task': 'Generate file hashes recursively for directory tree',
            'cmd': 'ssdeep -r *',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Compare signature files to detect overlapping entries',
            'cmd': 'ssdeep -r /etc >list1.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Detect source code reuse by comparing file similarities',
            'cmd': 'ssdeep -b foo.txt >hashes.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Detect file similarities using fuzzy hash matching',
            'cmd': 'ssdeep -b -m hashes.txt bar.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
    ],
    'strings': [
        {
            'task': 'Extract human-readable strings from binary files for analysis',
            'cmd': 'strings /bin/ls',
            'src': 'https://www.commandinline.com/strings-command-cheat-sheet/',
        },
        {
            'task': 'Extract hidden text from binary files for analysis',
            'cmd': 'strings -a firmware.bin',
            'src': 'https://www.commandinline.com/strings-command-cheat-sheet/',
        },
        {
            'task': 'Extract human-readable strings from binary files for analysis',
            'cmd': 'strings -n 8 binary.exe',
            'src': 'https://www.commandinline.com/strings-command-cheat-sheet/',
        },
        {
            'task': 'Extract readable strings from binary files for analysis',
            'cmd': 'strings $file > $file.txt',
            'src': 'https://ioflood.com/blog/strings-linux-command/',
        },
        {
            'task': 'Extract human-readable strings from binary with hex offsets',
            'cmd': 'strings -tx /bin/ls | head',
            'src': 'https://www.commandinline.com/strings-command-cheat-sheet/',
        },
        {
            'task': 'Extract data section strings from binary files',
            'cmd': 'strings -d executable_file',
            'src': 'https://www.tutorialspoint.com/unix_commands/strings.htm',
        },
    ],
    'tcpflow': [
        {
            'task': 'Extract and decode TCP flows from a pcap capture for analysis',
            'cmd': 'tcpflow -r eth0.pcap',
            'src': 'https://blog.rootshell.be/2009/04/15/forensics-reconstructing-data-from-pcap-files/',
        },
        {
            'task': 'Reconstruct TCP sessions from multiple pcap files',
            'cmd': 'tcpflow -o out -a -l *.pcap',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
        {
            'task': 'Reconstruct network flows from pcap for analysis',
            'cmd': 'tcpflow -a -o outdir -Fk -r packets.pcap',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
    ],
    'testdisk': [
        {
            'task': 'Recover partitions and repair filesystems from disk images',
            'cmd': 'testdisk image.dd to work on a raw disk image',
            'src': 'https://www.cgsecurity.org/wiki/TestDisk_Step_By_Step',
        },
    ],
    'tshark': [
        {
            'task': 'Exclude ARP traffic during capture',
            'cmd': 'tshark -f !arp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Generate protocol hierarchy statistics for network traffic analysis',
            'cmd': 'tshark -z io,phs',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Capture 100 packets excluding ARP traffic for analysis',
            'cmd': 'tshark -c 100 -f !arp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Generate TCP conversation statistics',
            'cmd': 'tshark -q -z conv,tcp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Capture 100 packets for network analysis',
            'cmd': 'tshark -c 100 -n -w 100pkts.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
    ],
    'tsk_gettimes': [
        {
            'task': 'Collect time data from disk image for analysis',
            'cmd': 'tsk_gettimes ./image.dd > body.txt',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tsk_gettimes/',
        },
    ],
    'tsk_recover': [
        {
            'task': 'Recover deleted files from disk image',
            'cmd': 'tsk_recover image.dd output_dir/',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
    ],
    'vshadowinfo': [
        {
            'task': 'Display Volume Shadow Snapshot volume information',
            'cmd': 'vshadowinfo /dev/sda1',
            'src': 'https://manpages.debian.org/testing/libvshadow-utils/vshadowinfo.1.en.html',
        },
        {
            'task': 'Extract shadow copy metadata from disk image',
            'cmd': 'vshadowinfo -o <partition_byte_offset> disk.raw',
            'src': 'https://github.com/project-dfir/dfir-lab/blob/main/module-24-anti-forensics-vss/README.md',
        },
    ],
    'vshadowmount': [
        {
            'task': 'Mount shadow volumes to access historical disk states',
            'cmd': 'vshadowmount -o <partition_byte_offset> disk.raw /mnt/vss',
            'src': 'https://github.com/project-dfir/dfir-lab/tree/main/module-24-anti-forensics-vss',
        },
        {
            'task': 'Mount VSS volume to access shadow copy data',
            'cmd': 'vshadowmount /dev/sda2 /mnt/fuse',
            'src': 'https://github.com/libyal/libvshadow/wiki/Mounting',
        },
        {
            'task': 'Mount VSS volume from raw image for access',
            'cmd': 'vshadowmount -X allow_root image.raw /mnt/fuse',
            'src': 'https://github.com/libyal/libvshadow/wiki/Mounting',
        },
    ],
    'xlmdeobfuscator': [
        {
            'task': 'Deobfuscate macros in Excel documents for analysis',
            'cmd': 'xlmdeobfuscator --file document.xlsm',
            'src': 'https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/README.md',
        },
        {
            'task': 'Extract macros from Excel document without deobfuscation',
            'cmd': 'xlmdeobfuscator --file document.xlsm -x',
            'src': 'https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/README.md',
        },
        {
            'task': 'Deobfuscate Excel macros using configuration file',
            'cmd': 'xlmdeobfuscator --file document.xlsm -c default.config',
            'src': 'https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/README.md',
        },
        {
            'task': 'Deobfuscate Excel macro code and export to JSON',
            'cmd': 'xlmdeobfuscator --file document.xlsm --export-json result.json',
            'src': 'https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/README.md',
        },
        {
            'task': 'Deobfuscate Excel macro code for analysis',
            'cmd': 'xlmdeobfuscator --file document.xlsm --no-indent --output-formula-format "[[INT-FORMULA]]"',
            'src': 'https://github.com/DissectMalware/XLMMacroDeobfuscator/blob/master/README.md',
        },
    ],
    'xortool': [
        {
            'task': 'Analyze XOR-encrypted files to find keys and determine key lengths',
            'cmd': 'xortool file.bin',
            'src': 'https://github.com/hellman/xortool/blob/master/README.md',
        },
        {
            'task': 'Decrypt XOR-encrypted hex file using space character set analysis',
            'cmd': "xortool -x -c ' ' file.hex",
            'src': 'https://github.com/hellman/xortool/blob/master/README.md',
        },
        {
            'task': 'Analyze XOR-encrypted files to determine key lengths and recover plaintext',
            'cmd': 'xortool -l 11 -c 20 file.bin',
            'src': 'https://github.com/hellman/xortool/blob/master/README.md',
        },
        {
            'task': 'Decrypt XOR-encrypted data with brute force and base64 charset',
            'cmd': 'xortool -b -f -l 23 -t base64 message.enc',
            'src': 'https://github.com/hellman/xortool/blob/master/README.md',
        },
        {
            'task': 'Decrypt XOR-encrypted files using character frequency analysis',
            'cmd': 'xortool tool_xored -c 20',
            'src': 'https://github.com/hellman/xortool/blob/master/README.md',
        },
    ],
    'xxd': [
        {
            'task': 'Convert hex dumps back to original binary data',
            'cmd': 'xxd -r',
            'src': 'https://commandlinux.com/man-page/man1/xxd/',
        },
        {
            'task': 'Recover original data from hexdump',
            'cmd': 'xxd -r -i',
            'src': 'https://commandlinux.com/man-page/man1/xxd/',
        },
        {
            'task': 'Display binary file contents as hex for analysis',
            'cmd': 'xxd file.bin',
            'src': 'https://www.commandinline.com/xxd-command-cheat-sheet/',
        },
        {
            'task': 'Analyze binary data at bit level',
            'cmd': 'xxd -b file.bin',
            'src': 'https://www.commandinline.com/xxd-command-cheat-sheet/',
        },
        {
            'task': 'Convert binary file to uppercase hexadecimal dump for analysis',
            'cmd': 'xxd -u file.bin',
            'src': 'https://www.commandinline.com/xxd-command-cheat-sheet/',
        },
        {
            'task': 'Inspect binary file contents in detailed hex format',
            'cmd': 'xxd -g 1 file.bin',
            'src': 'https://www.commandinline.com/xxd-command-cheat-sheet/',
        },
    ],
}
