"""Worked command lines, extracted from real pages.

Generated by scripts/build_invocations.py. Every `cmd` appeared
character for character in the page named by `src`; only `task` was
written, and it went through a gate. Do not edit by hand -- rerun the
script. Hand-written invocations belong in ENRICHMENT, which wins.
"""
from __future__ import annotations

INVOCATIONS: dict[str, list[dict]] = {
    'bdeinfo': [
        {
            'task': 'Retrieve BitLocker encryption details from a drive',
            'cmd': 'bdeinfo -p Password /dev/sda1',
            'src': 'https://manpages.ubuntu.com/manpages/bionic/man1/bdeinfo.1.html',
        },
        {
            'task': 'Extract BitLocker encryption details from disk image',
            'cmd': 'bdeinfo -o $((512*128)) image.dd',
            'src': 'https://www.aldeid.com/wiki/Category:Encryption/Bitlocker',
        },
        {
            'task': 'Extract BitLocker volume details including recovery key and encryption method',
            'cmd': 'bdeinfo -o $((512*2048)) ~/xmount_pount/Bitlocker_physisch_test.dd',
            'src': 'https://bebinary4n6.blogspot.com/2020/01/how-to-handle-bitlocker-encrypted.html',
        },
    ],
    'binwalk': [
        {
            'task': 'Scan firmware for embedded files and file systems',
            'cmd': 'binwalk firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
        {
            'task': 'Extract embedded files from firmware image',
            'cmd': 'binwalk -e firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
        {
            'task': 'Detect encrypted or compressed sections via entropy analysis',
            'cmd': 'binwalk -E firmware.bin',
            'src': 'https://www.hardbreak.wiki/hardware-hacking/basics/tools/software-tools/binwalk',
        },
    ],
    'chainsaw': [
        {
            'task': 'Detect missing log records and time gaps',
            'cmd': './chainsaw analyse gaps ./Logs/',
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
        {
            'task': 'Search EVTX logs for mimikatz activity',
            'cmd': './chainsaw search mimikatz -i evtx_attack_samples/',
            'src': 'https://github.com/WithSecureLabs/chainsaw',
        },
    ],
    'clamscan': [
        {
            'task': 'Scan entire directory tree for malware',
            'cmd': 'clamscan --recursive .',
            'src': 'https://docs.clamav.net/manual/Usage/Scanning.html',
        },
        {
            'task': 'Full system malware scan recursively',
            'cmd': 'clamscan --recursive /',
            'src': 'https://docs.clamav.net/manual/Usage/Scanning.html',
        },
        {
            'task': 'Detect malware across entire system',
            'cmd': 'clamscan.exe --recursive C:\\',
            'src': 'https://docs.clamav.net/manual/Usage/Scanning.html',
        },
    ],
    'ewfacquire': [
        {
            'task': 'Create EWF image from device or file',
            'cmd': 'ewfacquire /dev/sda',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Convert RAW to EWF or image a device',
            'cmd': 'ewfacquire myfile.raw',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Convert split optical disc RAW to EWF image',
            'cmd': 'ewfacquire -T optical.cue optical.iso',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Convert RAW image to EWF format',
            'cmd': 'ewfacquire -c best -m fixed -t myfile -S 1T -u [-q] myfile.raw',
            'src': 'https://forensics.wiki/libewf/',
        },
    ],
    'ewfexport': [
        {
            'task': 'Convert EWF image to RAW or another EWF format',
            'cmd': 'ewfexport image.E01',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Export files from logical EWF image',
            'cmd': 'ewfexport image.L01',
            'src': 'https://forensics.wiki/libewf/',
        },
    ],
    'ewfinfo': [
        {
            'task': 'Check EWF image details post-acquisition',
            'cmd': 'ewfinfo /Cases/001/001_2017_USB_Gold.E01',
            'src': 'https://dfir.science/2017/11/EWF-Tools-working-with-Expert-Witness-Files-in-Linux.html',
        },
    ],
    'ewfmount': [
        {
            'task': 'Mount EWF image to a folder for forensic analysis',
            'cmd': 'ewfmount image.E01 <folder>',
            'src': 'https://kb.offsec.nl/tools/forensics/ewf-tools/',
        },
        {
            'task': 'Mount EWF image to access its file system',
            'cmd': 'ewfmount image.E01 mount_point',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Mount logical image to access files',
            'cmd': 'ewfmount -f files image.L01 mount_point',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Mount EWF image to access disk as physical device',
            'cmd': 'ewfmount /Cases/001/001_2017_USB_Gold.E01 /mnt/ewf',
            'src': 'https://dfir.science/2017/11/EWF-Tools-working-with-Expert-Witness-Files-in-Linux.html',
        },
        {
            'task': 'Mount EWF image to a folder for file system access',
            'cmd': 'ewfmount image.E01 <folder>',
            'src': 'https://hanifi.ca/tools/forensics/ewf-tools/',
        },
    ],
    'ewfverify': [
        {
            'task': 'Verify EWF image integrity and validity',
            'cmd': 'ewfverify image.E01',
            'src': 'https://forensics.wiki/libewf/',
        },
        {
            'task': 'Verify EWF file integrity against original data',
            'cmd': 'ewfverify floppy.E01',
            'src': 'https://www.mankier.com/1/ewfverify',
        },
        {
            'task': 'Verify data integrity of E01 file against stored hash',
            'cmd': 'ewfverify -f files logical.E01',
            'src': 'https://www.mankier.com/1/ewfverify',
        },
        {
            'task': 'Verify EWF image integrity after acquisition',
            'cmd': 'ewfverify /Cases/001/001_2017_USB_Gold.E01',
            'src': 'https://dfir.science/2017/11/EWF-Tools-working-with-Expert-Witness-Files-in-Linux.html',
        },
    ],
    'foremost': [
        {
            'task': 'Carve JPEGs, PDFs, DOCs, XLS from disk image',
            'cmd': 'foremost -t doc,jpg,pdf,xls -i image.dd',
            'src': 'https://www.kali.org/tools/foremost/',
        },
    ],
    'icat': [
        {
            'task': 'Extract file content from disk image using inode',
            'cmd': 'icat image.dd <inode> > file_recovered',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
        {
            'task': 'Recover file content by inode from disk image',
            'cmd': 'icat image.dd 1234 > recovered_file.txt',
            'src': 'https://nicholasr512.github.io/Linux_and_Kali_Linux_Guide/Kali%20Tools/10%20-%20Digital%20Forensics/Sleuthkit/',
        },
        {
            'task': 'Recover deleted file from evidence image',
            'cmd': 'icat -r -o 2048 "$EVIDENCE" 54321 > recovered_file.bin',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'mactime': [
        {
            'task': 'Generate timeline of file events from MAC time data',
            'cmd': 'mactime -b body.txt -d > timeline.csv',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Generate timeline with file paths and timestamps',
            'cmd': 'mactime -b "$OUTPUT/body.txt" -d -z UTC > "$OUTPUT/timeline.csv"',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
        {
            'task': 'Generate timeline of file events within specific date range',
            'cmd': 'mactime -b body.txt -d -z UTC 2026-01-14..2026-01-15 > incident_timeline.csv',
            'src': 'https://oneuptime.com/blog/post/2026-03-02-how-to-use-sleuth-kit-for-file-system-forensics-on-ubuntu/view',
        },
    ],
    'ngrep': [
        {
            'task': 'Monitor SMTP traffic on all network interfaces',
            'cmd': 'ngrep -d any port 25',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Capture HTTP traffic details line by line',
            'cmd': 'ngrep -W byline port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search for specific strings in network traffic data',
            'cmd': "ngrep -w 'm' -I /tmp/dns.dump",
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Search for HTTP traffic in a packet capture file',
            'cmd': 'ngrep -I /tmp/dns.dump port 80',
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
        {
            'task': 'Capture error messages in network syslog traffic',
            'cmd': "ngrep -d any 'error' port syslog",
            'src': 'https://github.com/jpr5/ngrep/blob/master/EXAMPLES.md',
        },
    ],
    'oleid': [
        {
            'task': 'Analyze OLE files for macros, encryption, and embedded objects',
            'cmd': 'oleid <file>',
            'src': 'https://github.com/decalage2/oletools/wiki/oleid',
        },
    ],
    'olevba': [
        {
            'task': 'Analyze VBA macros in documents for malicious code',
            'cmd': 'olevba file.doc',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Scan VBA source code for obfuscated strings and malicious content',
            'cmd': 'olevba source_code.vba',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Decode obfuscated strings in VBA macro for analysis',
            'cmd': 'olevba file.doc --decode',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Analyze document macros by revealing deobfuscated VBA code',
            'cmd': 'olevba file.doc --reveal',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
        {
            'task': 'Analyze VBA macros in multiple files for malware detection',
            'cmd': 'olevba "MalwareZoo/VBA/*"',
            'src': 'https://github.com/decalage2/oletools/wiki/olevba',
        },
    ],
    'photorec': [
        {
            'task': 'Recover files from raw disk image',
            'cmd': 'photorec image.dd to carve a raw disk image',
            'src': 'https://www.cgsecurity.org/wiki/PhotoRec_Step_By_Step',
        },
        {
            'task': 'Recover files from Encase EWF image',
            'cmd': 'photorec image.E01 to recover files from an Encase EWF image',
            'src': 'https://www.cgsecurity.org/wiki/PhotoRec_Step_By_Step',
        },
    ],
    'sigtool': [
        {
            'task': 'Identify false positive virus signature in database',
            'cmd': 'sigtool --unpack=FILE',
            'src': 'https://docs.clamav.net/manual/Usage/SignatureManagement.html',
        },
    ],
    'ssdeep': [
        {
            'task': 'Generate file hashes recursively for directory tree',
            'cmd': 'ssdeep -r *',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Compare signature files to detect overlapping entries',
            'cmd': 'ssdeep -r /etc >list1.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Compare signature files to find matching or similar entries',
            'cmd': 'ssdeep -r /usr >list2.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Detect source code reuse by comparing file similarities',
            'cmd': 'ssdeep -b foo.txt >hashes.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Detect file similarities using fuzzy hash matching',
            'cmd': 'ssdeep -b -m hashes.txt bar.txt',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
        {
            'task': 'Check if file matches known signature for identification',
            'cmd': 'ssdeep -b -m sig.txt partial.avi',
            'src': 'https://ssdeep-project.github.io/ssdeep/usage.html',
        },
    ],
    'tcpflow': [
        {
            'task': 'Decode TCP flows from pcap to extract HTTP data and files',
            'cmd': 'tcpflow -r eth0.pcap',
            'src': 'https://blog.rootshell.be/2009/04/15/forensics-reconstructing-data-from-pcap-files/',
        },
        {
            'task': 'Reconstruct network flows from multiple pcap files into output directory',
            'cmd': 'tcpflow -o out -a -l *.pcap',
            'src': 'https://www.systutorials.com/docs/linux/man/1-tcpflow/',
        },
    ],
    'testdisk': [
        {
            'task': 'Recover partitions and repair filesystems from disk images',
            'cmd': 'testdisk image.dd to work on a raw disk image',
            'src': 'https://www.cgsecurity.org/wiki/TestDisk_Step_By_Step',
        },
        {
            'task': 'Recover files from Encase EWF image',
            'cmd': 'testdisk image.E01 to recover files from an Encase EWF image',
            'src': 'https://www.cgsecurity.org/wiki/TestDisk_Step_By_Step',
        },
    ],
    'tshark': [
        {
            'task': 'Exclude ARP traffic during capture',
            'cmd': 'tshark -f !arp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Generate protocol hierarchy statistics for network traffic analysis',
            'cmd': 'tshark -z io,phs',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Capture 100 packets excluding ARP traffic for analysis',
            'cmd': 'tshark -c 100 -f !arp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Generate TCP conversation statistics',
            'cmd': 'tshark -q -z conv,tcp',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
        {
            'task': 'Capture 100 packets for network analysis',
            'cmd': 'tshark -c 100 -n -w 100pkts.pcap',
            'src': 'https://docsislab.wordpress.com/packet-capture/wireshark-command-line/',
        },
    ],
}
